from typing import Protocol


class BotRuntimePort(Protocol):
    async def start_bot(self, token: str) -> object: ...

    async def stop_bot(self, bot_id: int, *, token: str | None = None) -> None: ...

    async def stop_all(self) -> None: ...
