"""initial

Revision ID: 2bb4438ada27
Revises:
Create Date: 2026-05-14 12:24:48.003815

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bb4438ada27"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("encrypted_token", sa.String(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_game_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("bot_id"),
    )
    op.create_index(
        op.f("ix_bots_last_game_attempt_at"),
        "bots",
        ["last_game_attempt_at"],
        unique=False,
    )
    op.create_table(
        "players",
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("bot_id", "chat_id", "user_id"),
    )
    op.create_table(
        "stats",
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "win_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_win", sa.Date(), nullable=True),
        sa.Column(
            "lose_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_lose", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("bot_id", "chat_id", "user_id"),
        sa.UniqueConstraint(
            "bot_id", "chat_id", "last_lose", name="uq_bot_chat_lose_day"
        ),
        sa.UniqueConstraint(
            "bot_id", "chat_id", "last_win", name="uq_bot_chat_win_day"
        ),
    )
    op.create_index(
        "ix_stats_loser_top",
        "stats",
        ["bot_id", "chat_id", sa.literal_column("lose_count DESC")],
        unique=False,
    )
    op.create_index(
        "ix_stats_winner_top",
        "stats",
        ["bot_id", "chat_id", sa.literal_column("win_count DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stats_winner_top", table_name="stats")
    op.drop_index("ix_stats_loser_top", table_name="stats")
    op.drop_table("stats")
    op.drop_table("players")
    op.drop_index(op.f("ix_bots_last_game_attempt_at"), table_name="bots")
    op.drop_table("bots")
    # ### end Alembic commands ###
