PLAYER_REGISTRATION_DISABLED = "Регистрация игроков временно закрыта."
PLAYER_REGISTERED = "Ты в игре!"
PLAYER_NOT_IN_LIST = "Тебя нет в списках игроков."
PLAYER_ALREADY_NOT_IN_LIST = "Тебя и так нет в списках игроков."
PLAYER_UNREGISTERED = "Ты вышел из игры. Но мы всё помним... 😉"
PLAYER_LIST_EMPTY = "Никто не зарегистрировался в игре."
PLAYER_LIST_HEADER = "Участники игры в этом чате:\n"

DRAW_ALREADY_PLAYED = "Сегодня выбор уже сделан!"
DRAW_NO_PLAYERS = "Никто не зарегистрировался!"
